//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public int MenuId { get; set; }
        public int Quantity { get; set; }
        public string OrderedBy { get; set; }
        public int ProductId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual User User { get; set; }
        public virtual Price Price { get; set; }
    }
}
